### ISSUE TITLE
出现一些问题

### ISSUE THREAD

**Issue by kyomeki** [mybdye/Project-E#1]
```
Run python3 ./main.py
Traceback (most recent call last):
- loading...
  File "/Users/runner/work/Project-E/Project-E/./main.py", line 281, in <module>
- title: EUserv KundenCenter (2.[17](https://github.com/kyomeki/Project-E/runs/6237097695?check_suite_focus=true#step:4:17).1_[20](https://github.com/kyomeki/Project-E/runs/6237097695?check_suite_focus=true#step:4:20)[22](https://github.com/kyomeki/Project-E/runs/6237097695?check_suite_focus=true#step:4:22)0228)
- login_euserv
- fill user id
    login_euserv()
  File "/Users/runner/work/Project-E/Project-E/./main.py", line [25](https://github.com/kyomeki/Project-E/runs/6237097695?check_suite_focus=true#step:4:25)8, in login_euserv
    renew()
  File "/Users/runner/work/Project-E/Project-E/./main.py", line 1[31](https://github.com/kyomeki/Project-E/runs/6237097695?check_suite_focus=true#step:4:31), in renew
    wait_until(Text('vServer').exists)
  File "/usr/local/lib/python3.9/site-packages/helium/__init__.py", line 473, in wait_until
- fill password
    _get_api_impl().wait_until_impl(condition_fn, timeout_secs, interval_secs)
  File "/usr/local/lib/python3.9/site-packages/helium/_impl/__init__.py", line [35](https://github.com/kyomeki/Project-E/runs/6237097695?check_suite_focus=true#step:4:35)7, in wait_until_impl
- click button [Login]
- CAPTCHA Not Found
- login success
- renew
    wait.until(condition)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Error: Process completed with exit code 1.
```

**Comment by mybdye** [comment]
更新了 你再试下

**Comment by kyomeki** [comment]
https://github.com/kyomeki/Project-E/runs/6238580114

**Comment by kyomeki** [comment]
还是无法正常工作

**Comment by mybdye** [comment]
登陆后页面跳转，有些元素查不到，我晚点看看

**Comment by mybdye** [comment]
> > 登陆后页面跳转，有些元素查不到，我晚点看看
> 
> 登录也会验证邮件PIN码

👍，记下了

**Comment by mybdye** [comment]
@kyomeki  你更新仓库再试试
@kkkyg 看了下是那个‘customer data confirmation’ 卡住了😮‍💨

**Comment by kyomeki** [comment]
> @kyomeki 你更新仓库再试试 @kkkyg 看了下是那个‘customer data confirmation’ 卡住了😮‍💨

https://github.com/kyomeki/Project-E/runs/6334886371?check_suite_focus=true

**Comment by mybdye** [comment]
> > @kyomeki 你更新仓库再试试 @kkkyg 看了下是那个‘customer data confirmation’ 卡住了😮‍💨
> 
> 还是不行 看起来是验证码问题（？ 我已经把转发和解析设置好了啊🤔 https://github.com/kyomeki/Project-E/runs/6334886371?check_suite_focus=true

OK，看到图了，我这边一直没遇到登陆这个pin，等下更新
http://mjjzp.cf/img/2022/05/07/bdff15790ab8e.png

**Comment by mybdye** [comment]
@kyomeki 麻烦再更新试下，我这边本地没法重现登陆pin，你本地登陆提示需要pin不

**Comment by kyomeki** [comment]
https://github.com/kyomeki/Project-E/runs/6338736730?check_suite_focus=true
@mybdye 还是不行 很奇怪😂

**Comment by mybdye** [comment]
> https://github.com/kyomeki/Project-E/runs/6338736730?check_suite_focus=true @mybdye 还是不行 很奇怪😂

@kyomeki  你的 pin 解析估计跟我的不一样，json 文件 丢一个我康康
<img width="370" alt="image" src="https://user-images.githubusercontent.com/21116709/167282882-2f743845-3fec-4be5-ba5e-50f21cf985f0.png">
