### ISSUE TITLE
登陆 PIN 填充 Issue

### ISSUE THREAD

**Issue by takemyview** [mybdye/Project-E#2]
Traceback (most recent call last):
  File "/Users/runner/work/eukeep/eukeep/./main.py", line 336, in <module>
- loading...
- title: EUserv KundenCenter (2.17.1a_202204[15](https://github.com/takemyview/eukeep/runs/6641134713?check_suite_focus=true#step:5:16))
- login_euserv
- fill user id
- fill password
- click button [Login]
*** To finish the login process enter the PIN that you receive via email. ***
- get pin
- pin: 854218
- fill pin
    login_euserv()
  File "/Users/runner/work/eukeep/eukeep/./main.py", line 272, in login_euserv
    write(pin, into=S('@auth'))
  File "/usr/local/lib/python3.9/site-packages/helium/__init__.py", line [16](https://github.com/takemyview/eukeep/runs/6641134713?check_suite_focus=true#step:5:17)6, in write
    _get_api_impl().write_impl(text, into)
  File "/usr/local/lib/python3.9/site-packages/helium/_impl/__init__.py", line 37, in f_decorated
    result = f(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/helium/_impl/__init__.py", line 56, in f_decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/helium/_impl/__init__.py", line [17](https://github.com/takemyview/eukeep/runs/6641134713?check_suite_focus=true#step:5:18)0, in write_impl
    self._handle_alerts(
  File "/usr/local/lib/python3.9/site-packages/helium/_impl/__init__.py", line 195, in _handle_alerts
    return no_alert(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/helium/_impl/__init__.py", line [18](https://github.com/takemyview/eukeep/runs/6641134713?check_suite_focus=true#step:5:19)1, in _write_no_alert
    self._manipulate(into, _write)
  File "/usr/local/lib/python3.9/site-packages/helium/_impl/__init__.py", line [30](https://github.com/takemyview/eukeep/runs/6641134713?check_suite_focus=true#step:5:31)1, in _manipulate
    driver.last_manipulated_element = gui_or_web_elt.perform(action)
  File "/usr/local/lib/python3.9/site-packages/helium/_impl/__init__.py", line 648, in perform
    raise LookupError()
LookupError
Error: Process completed with exit code 1.

**Comment by takemyview** [comment]
你好，我已经用了最新版的项目仓库，看后面是 lookup error 查找出错。

**Comment by mybdye** [comment]
> 
这里的情况是遇到了登陆就要求PIN，但是我本地调试和 github action 都没遇到，所以估计
write(pin, into=S('@auth')) 这个（pin 输入框）元素 @auth 没写对，导致查找出错。

**Comment by takemyview** [comment]
还是lookup error，而且弹出一堆信息。
https://github.com/takemyview/eukeep/runs/6643405237?check_suite_focus=true

**Comment by mybdye** [comment]
拿到元素名了，你更新再看看

**Comment by takemyview** [comment]
谢谢，可以了，没报错了。

因为我今天只在 mailparser 设置了 EUserv - Attempted Login 这个邮件的转发，后面 续期的 EUserv - PIN for the Confirmation of a Security Check 还没到续期日期所以我还没有邮件可设置，31日我才能设置。

所以我还想知道，项目代码有没有获取两次pin码，一次是EUserv - Attempted Login，一次是EUserv - PIN for the Confirmation of a Security Check。

**Comment by mybdye** [comment]
> 谢谢，可以了，没报错了。
> 
> 因为我今天只在 mailparser 设置了 EUserv - Attempted Login 这个邮件的转发，后面 续期的 EUserv - PIN for the Confirmation of a Security Check 还没到续期日期所以我还没有邮件可设置，31日我才能设置。
> 
> 所以我还想知道，项目代码有没有获取两次pin码，一次是EUserv - Attempted Login，一次是EUserv - PIN for the Confirmation of a Security Check。

标题含有  `EUserv - PIN` 的邮件转发到mailparser 即可;
line 142-156 续期 get pin;
line 267-282 登陆 get pin.

**Comment by takemyview** [comment]
好的，谢谢作者抽空帮我解决问题，谢谢！
